# Generated by Django 5.1.4 on 2025-01-09 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_rename_seat_occupiedseat'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='background/'),
        ),
        migrations.AddField(
            model_name='movie',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
